#!/usr/bin/env python
#coding: utf-8
questions = [ 
        {
            "question": "Оператор вывода на экран?", 
            "answers": [
                {"text": "1 echo", "is_true": False},
                {"text": "2 print", "is_true": True},
                {"text": "3 output", "is_true": False}
            ] 
        },  
        
        {
            "question": "Оператор цикла?", 
            "answers": [
                {"text": "1 for", "is_true": True},
                {"text": "2 if", "is_true": False},
                {"text": "3 loop", "is_true": False}
            ] 
        },
        
    ]
 
for question in questions:
    print(question["question"])
    for answer in question["answers"]:
        print(answer["text"])
    user_answer = input()
    print question["answers"][user_answer-1]
    if question["answers"][user_answer-1]["is_true"] == True:
        print("\033[94m"+"Ответ ВЕРНЫЙ!!!"+"\033[0m")
    else:
        print("\033[93m"+"Неправильно!"+"\033[0m")
